import logging
import os
from typing import Dict, Optional
from developer.models import ProjectInfo

logger = logging.getLogger("AURA.Developer.Documentation")


class DocumentationGenerator:
    """
    Generates README files, architecture overviews, and API documentation markdown documents.
    """

    def generate_readme(self, project_info: ProjectInfo) -> str:
        content = f"""# {project_info.name}

Automated project documentation generated by AURA AI Operating System.

## Architecture Overview
- **Tech Stack**: {project_info.tech_stack.value.capitalize()}
- **File Count**: {project_info.file_count}
- **Directory Count**: {project_info.directory_count}

## Getting Started

### Installation
```bash
# Install dependencies
npm install  # or pip install -r requirements.txt
```

### Running Development Server
```bash
npm run dev  # or python main.py
```
"""
        readme_path = os.path.join(project_info.project_path, "README.md")
        try:
            with open(readme_path, "w", encoding="utf-8") as fh:
                fh.write(content)
            logger.info(f"Generated README.md at {readme_path}")
        except Exception as e:
            logger.error(f"Failed to write README.md: {e}")

        return content
