from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional
import time


class RiskLevel(Enum):
    """Risk levels for recommendations and decision policies."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class UserPreference:
    """Represents a learned or explicit user preference."""
    key: str
    value: Any
    confidence_score: float = 1.0
    source: str = "inferred"  # "explicit" or "inferred"
    updated_at: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "key": self.key,
            "value": self.value,
            "confidence_score": self.confidence_score,
            "source": self.source,
            "updated_at": self.updated_at,
        }


@dataclass
class WorkflowPattern:
    """Represents a recurring workflow pattern and execution history."""
    pattern_id: str
    goal_query: str
    suggested_sequence: List[str]
    success_count: int = 0
    failure_count: int = 0
    confidence_score: float = 0.5
    last_executed: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "pattern_id": self.pattern_id,
            "goal_query": self.goal_query,
            "suggested_sequence": self.suggested_sequence,
            "success_count": self.success_count,
            "failure_count": self.failure_count,
            "confidence_score": self.confidence_score,
            "last_executed": self.last_executed,
        }


@dataclass
class Recommendation:
    """Explainable and dismissible suggestion generated by Adaptive Learning."""
    recommendation_id: str
    title: str
    reason: str
    supporting_evidence: List[str]
    confidence_score: float
    risk_level: RiskLevel = RiskLevel.LOW
    dismissed: bool = False
    created_at: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "recommendation_id": self.recommendation_id,
            "title": self.title,
            "reason": self.reason,
            "supporting_evidence": self.supporting_evidence,
            "confidence_score": self.confidence_score,
            "risk_level": self.risk_level.value,
            "dismissed": self.dismissed,
            "created_at": self.created_at,
        }


@dataclass
class ConfidenceRating:
    """Transparent confidence rating with supporting evidence."""
    score: float  # 0.0 to 1.0
    evidence: List[str]
    risk_level: RiskLevel
    reasoning: str
